#!/bin/bash

#
# Copyright (C) 2018 Heinrich-Heine-Universitaet Duesseldorf, Institute of Computer Science, Department Operating Systems
#
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
#

config()
{
    local key=$1
    local value=$2

    if [ "$key" ] && [ ! "$value" ]; then
        cdepl_configuration_get ${@:1}
    else 
        cdepl_configuration_set ${@:1}
        cdepl_configuration_save
    fi
}

cluster()
{
    cdepl_cluster_main ${@:1}
}

install()
{
    echo "Currently not implemented"
}

run()
{
    cdepl_run_main ${@:1}
}

kill()
{
    cdepl_kill_main ${@:1}
}

help()
{
    printf "Commands available: 
    config: Get configuration values or change them
    cluster: Manage the current cluster, e.g. node allocation, get status
    install: Install a supported application package on the cluster
    run: Run a supported application on the cluster
    kill: Kill a supported application running on the cluster
"
}

###############
# Entry point #
###############

source "util"
source "cluster/main"
source "kill/main"
source "run/main"

echo "Type 'help' to get a list of available commands. Use tab for auto completion for command arguments"
