#!/bin/bash

#
# Copyright (C) 2018 Heinrich-Heine-Universitaet Duesseldorf, Institute of Computer Science, Department Operating Systems
#
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
#

__CDEPL_KILL_CUR_OUT_PATH=""
__CDEPL_KILL_LOCAL_TMP_PATH=""

##
# Get the currently set out path for logfiles, configs etc of the deployed
# applications
#
# Return stdout: Current path set
##
cdepl_run_get_cur_out_path()
{
	echo "$__CDEPL_KILL_CUR_OUT_PATH"
}

##
# Get the currently set local tmp path used by the application modules to 
# download/upload configuration files to the local node/the cluster
##
cdepl_run_get_local_tmp_path()
{
	echo "$__CDEPL_KILL_LOCAL_TMP_PATH"
}

cdepl_kill_main()
{
	local module=$1
	local args=${@:2}

    if [ ! "$module" ]; then
	    util_log "Usage: kill <module> [args ...]"
	    return
    fi

    if [ ! -f "kill/$module" ]; then
        util_log_error "Missing kill module for \"$module\""
        return
    fi

    if [ ! "$(cdepl_cluster_get_alloc_node_count)" ]; then
        util_log_error "No node allocation was executed for current session, yet"
        return
    fi

    source "kill/$module"

    __cdepl_kill_setup_out_path $module

	_cdepl_kill_application $args
}

##
# Setup the output path for configuration files, log files, job scripts etc
# that are created during deployment. This location depends on the cluster
# implementation but uses the current user to put it either into his home
# directory or somewhere accessable.
#
# $1: User name of the account to use on the target cluster
##
__cdepl_kill_setup_out_path()
{
    local application_name=$1

	deployt_out_path=$(cdepl_cluster_out_path)

	__CDEPL_KILL_CUR_OUT_PATH="${deployt_out_path}/${application_name}_$(date '+%Y-%m-%d_%H-%M-%S-%3N')"
	eval __CDEPL_KILL_LOCAL_TMP_PATH="~/cdepl_tmp"

	cdepl_cluster_file_system_cmd "mkdir -p $__CDEPL_KILL_CUR_OUT_PATH"

	# create symlink to latest output folder
	cdepl_cluster_file_system_cmd "ln -sfn $__CDEPL_KILL_CUR_OUT_PATH/ $deployt_out_path/${application_name}"

	# This path is local for tmp downloads from the lucster
	mkdir -p $__CDEPL_KILL_LOCAL_TMP_PATH

	util_log "[kill] Deployment output path: $__CDEPL_KILL_CUR_OUT_PATH"
}
