#!/bin/bash

readonly __INFINISPAN_SERVER_CONFIG="infinispan-server.xml"

__INFINISPAN_PATH=""
__INFINISPAN_OUT_PATH=""
__INFINISPAN_OUT_DATA_PATH=""

##
# Initialize and setup Infinispan environment. This must be called before any other
# function of the Infinispan module.
#
# $1 Path to folder containing the unpacked Infinispan installation (with folders bin, lib etc)
##
cdepl_app_infinispan_init()
{
	local infinispan_path=$1

	__INFINISPAN_PATH="$(cdepl_cluster_file_system_cmd "realpath ${infinispan_path}")"
	__INFINISPAN_OUT_PATH="${__DEPLOY_CUR_OUT_PATH}"

	if [ ! "$__INFINISPAN_PATH" ] || [ "$(cdepl_cluster_file_system_cmd "[ -d ${__INFINISPAN_PATH} ] && echo \"1\"")" != "1" ]; then
		util_log_error_and_exit "[infinispan]: Path does not exist: ${__INFINISPAN_PATH}"
	fi

	util_log "[infinispan] Initialized: ${__INFINISPAN_PATH}"
	util_log "[infinispan] Output: ${__INFINISPAN_OUT_PATH}"

    __INFINISPAN_OUT_DATA_PATH="${__INFINISPAN_OUT_PATH}/data"

    # create log file output
    cdepl_cluster_file_system_cmd "mkdir -p ${__INFINISPAN_OUT_PATH}/log"
    cdepl_cluster_file_system_cmd "mkdir -p ${__INFINISPAN_OUT_DATA_PATH}"
}

##
# Start a Infinispan instance on the target node.
#
# $1 node_range_start Node id to start instance on (or range start)
# $2 node_range_end (optional) If specified, all nodes from the range start to
#    end are started
##
cdepl_app_infinispan_start_node()
{
	local node_range_start=$1
	local node_range_end=$2

	if [ "$node_range_end" ]; then
        local counter=0
		local pids=""

		for node in $(seq "$node_range_start" "$node_range_end"); do
			__cdepl_app_infinispan_start_node "$node" &
			pids="$pids $!"
        
			counter=$((counter + 1))

			# Parallel deploy in batches of 10 which is the default limit
			# for parallel connections on ssh servers, stay slightly below 
			# this limit (sometimes, 10 causes errors on multiplexing)
			if [ "$counter" -ge "8" ]; then
				wait $pids
				pids=""
				counter=0
			fi
		done

		wait $pids
	else
		__cdepl_app_infinispan_start_node "$node_range_start"
	fi
}

##
# Wait for a started Infinispan instance to be fully started.
#
# $1 node Target node id with started Infinispan instance
##
cdepl_app_infinispan_node_wait_started()
{
	local node=$1

	local logfile="${__INFINISPAN_OUT_PATH}/log/node${node}"

    local condition="Infinispan Server .* started in"

	util_log "[$node][infinispan] Waiting for startup: $condition"

	while true; do
		echo -n "."

		local success=$(cdepl_cluster_node_cmd "$node" "cat $logfile 2> /dev/null | grep '$condition'")

		if [ "$success" ]; then
			local pid=$(__cdepl_app_infinispan_get_instance_running_pid "$node")

			echo ""

			if [ ! "$pid" ]; then
				util_log_error_and_exit "[$node][infinispan] Could not find started process"
			fi

			util_log "[$node][infinispan] Started (pid: $pid)"

			break
		fi

		sleep 1.0
	done

	return 0
}

##
# Cleanup any still running or remaining/crashed instances on the target node
#
# $1 Target node id (or start node id of range if second parameter provided)
# $2 Optional: Node id range end (including) and first parameter is interpreted
#    as range start (including)
##
cdepl_app_infinispan_node_cleanup()
{
	local node_range_start=$1
	local node_range_end=$2

	if [ "$node_range_end" ]; then
		local pids=""

		for node in $(seq "$node_range_start" "$node_range_end"); do
			__cdepl_app_infinispan_cleanup "$node" &
			pids="$pids $!"
		done

		wait $pids
	else
		__cdepl_app_infinispan_cleanup "$node_range_start"
	fi
}

#################################################

__cdepl_app_infinispan_start_node()
{	
	local node=$1

	local logfile="${__INFINISPAN_OUT_PATH}/log/node${node}"
    local data_dir="${__INFINISPAN_OUT_DATA_PATH}/node${node}"
    local run_java=""

    if [ $JAVA_HOME ]; then
	    run_java=$JAVA_HOME/bin/java
    else
        run_java=`which java 2>/dev/null`
    fi

    util_log "[$node][infinispan] Starting instance, logfile: $logfile"

    local config=""

    local ip=$(cdepl_cluster_resolve_node_to_ip $node)

    config="$config -c clustered.xml"
    config="$config -Djboss.bind.address=$ip -Djboss.bind.address.management=$ip"
    config="$config -Djboss.server.data.dir=$data_dir"

    # Create out dir for data output
    cdepl_cluster_node_cmd "$node" "mkdir -p $data_dir"

    cdepl_cluster_node_cmd "$node" "cd $__INFINISPAN_PATH ; nohup ./bin/standalone.sh $config > $logfile 2>&1 &"
}

__cdepl_app_infinispan_get_instance_running_pid()
{
	local node=$1

	cdepl_cluster_node_cmd "$node" "pgrep -f 'infinispan'"
}

__cdepl_app_infinispan_cleanup()
{
	local node=$1

	util_log "[$node][infinispan] Cleanup..."

	local pid=$(__cdepl_app_infinispan_get_instance_running_pid "$node")

	if [ "$pid" ]; then
		# If we or someone else left some garbage processes on the node multiple
		# pids are returned
		for i in $pid; do
			local kill_out=$(cdepl_cluster_node_cmd "$node" "kill -9 $i 2>&1")

			if [ "$?" = "0" ] && [ ! "$kill_out" ]; then
				util_log "[$node][infinispan] Killed (pid: $i)"
			elif [ "$?" != "1" ]; then
				util_log_warn "[$node][infinispan] Killing $i failed, Infinispan instance(s) might stay alive"
			fi
		done
	fi
}

__cdepl_app_infinispan_create_config()
{
    local tmp_config="/tmp/$__INFINISPAN_SERVER_CONFIG"

    # Enable user code deployment to allow execution of the ycsb client
    # note: blacklist MUST contain something, otherwise everything is blacklisted (?!)
    # empty whitelist = everything whitelist'd (?)

	printf '%s' "
<infinispan xmlns=\"http://www.infinispan.com/schema/config\"
           xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"
           xsi:schemaLocation=\"http://www.infinispan.com/schema/config
           http://www.infinispan.com/schema/config/infinispan-config-3.10.xsd\">

    <user-code-deployment enabled=\"true\">
        <class-cache-mode>ETERNAL</class-cache-mode>
        <provider-mode>LOCAL_AND_CACHED_CLASSES</provider-mode>
        <blacklist-prefixes>com.foo</blacklist-prefixes>
        <whitelist-prefixes></whitelist-prefixes>
    </user-code-deployment>
</infinispan>
" > $tmp_config

    cdepl_cluster_upload_to_remote $tmp_config $__INFINISPAN_OUT_PATH
}