#!/bin/bash

#
# Copyright (C) 2018 Heinrich-Heine-Universitaet Duesseldorf, Institute of Computer Science, Department Operating Systems
#
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
#

# Includes
source "app/aerospike"

_cdepl_run_application()
{
	local cluster_group=$1

	if [ ! "$cluster_group" ]; then
		util_log "Usage: <user group on cluster>"
	fi

    local cluster_total_nodes=$(cdepl_cluster_get_alloc_node_count)
    local aerospike_path="$(cdepl_cluster_application_install_dir)/aerospike-server"
	local cluster_user=$(cdepl_cluster_get_user)

    cdepl_app_aerospike_init $aerospike_path $cluster_user $cluster_group

	for i in $(seq 0 $((cluster_total_nodes - 1))); do
		cdepl_app_aerospike_start_node $i
	done

	for i in $(seq 0 $((cluster_total_nodes - 1))); do
		cdepl_app_aerospike_wait_finished $i
	done
}