#!/bin/bash

#
# Copyright (C) 2018 Heinrich-Heine-Universitaet Duesseldorf, Institute of Computer Science, Department Operating Systems
#
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
#

# Includes
source "app/zookeeper"

ZK_PORT=2181

_cdepl_run_application()
{
    local target_node="$1"

    if [ ! "$target_node" ]; then
        util_log "Usage: <target node id to run on>"
        return
    fi

    local zookeeper_path="$(cdepl_cluster_application_install_dir)/zookeeper"
    local cluster_total_nodes=$(cdepl_cluster_get_alloc_node_count)

    if [ "$target_node" -ge "$cluster_total_nodes" ]; then
        util_log_error "Target node id $target_node is out of range of allocated node count $cluster_total_nodes"
        return
    fi

    cdepl_app_zookeeper_init $zookeeper_path

	# Start zookeeper instance and wait until started
	cdepl_app_zookeeper_start $target_node $ZK_PORT
	cdepl_app_zookeeper_wait_started $target_node
}